version: "3.7"

services:
    crawler:
        build:
            context: rate-my-bistro-crawler

    server:
        build:
            context: rate-my-bistro-server

    database:
        build:
            context: rate-my-bistro-database
        ports:
            - "8529:8529"
        environment:
            - ARANGO_NO_AUTH=0
            - ARANGO_ROOT_PASSWORD=iamroot
            - ARANGO_DB_NAME=bistro
            - ARANGO_DB_USER=bistrouser
            - ARANGO_DB_PASSWORD=bistropassword
        volumes:
            - arangoData:/var/lib/arangodb3

volumes:
    arangoData:
