version: "3.7"

services:
    crawler:
        build:
            context: rate-my-bistro-crawler


    server:
        build:
            context: rate-my-bistro-server


    database:
        image: arangodb/arangodb
        ports:
            - "8529:8529"
        environment:
            - ARANGO_NO_AUTH=1
