version: "3.7"

services:
    crawler:
        build:
            context: crawler
        env_file:
            - crawler/.env.example
        environment:
            - DATABASE_ADDRESS=http://database:8529
            - SWAGGER_API_DOC_LOCATION=swagger.json
            - GIN_MODE=release
        depends_on:
            - database
        ports:
            - "7331:7331"

    server:
        build:
            context: server

    database:
        build:
            context: database
        ports:
            - "8529:8529"
        environment:
            - ARANGO_RANDOM_ROOT_PASSWORD=1
            - ARANGO_DB_NAME=bistro
            - ARANGO_DB_USER=bistrouser
            - ARANGO_DB_PASSWORD=bistropassword
        volumes:
            - arangoData:/var/lib/arangodb3

volumes:
    arangoData:
