
name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{steps.version_bump.outputs.new_tag}}
    steps:
      - name: Github Tag Bump
        id: version_bump
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
  push:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2      
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to ghcr.io
        uses: docker/build-push-action@v2
        with:
          push: true
          context: database
          tags: ghcr.io/rate-my-bistro/database:latest, ghcr.io/rate-my-bistro/database:${{needs.release.outputs.release_tag}}
